// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eowkjduhaqvzdackzbly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvd2tqZHVoYXF2emRhY2t6Ymx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODg1NDIsImV4cCI6MjA3Mjk2NDU0Mn0.-1R1AgPUVKaBy76bvRrWXNAbTL8a3eH512mS9D84jz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});